version: '3.9'
services:
  user-service:
    build: ./microservices/user-service
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=mongodb+srv://hoangvutrannn:77pCHwjv1OwdqKuh@cluster1.7plzt.mongodb.net/?retryWrites=true&w=majority    
  
  waste-categories-service:
    build: ./microservices/waste-categories-service
    ports:
      - "8002:8002"
    environment:
      - MONGO_URL=mongodb+srv://hoangvutrannn:77pCHwjv1OwdqKuh@cluster1.7plzt.mongodb.net/?retryWrites=true&w=majority

  waste-items-service:
    build: ./microservices/waste-items-service
    ports:
      - "8003:8003"
    environment:
      - MONGO_URL=mongodb+srv://hoangvutrannn:77pCHwjv1OwdqKuh@cluster1.7plzt.mongodb.net/?retryWrites=true&w=majority

  challenges-service:
    build: ./microservices/challenges-service
    ports:
      - "8004:8004"
    environment:
      - MONGO_URL=mongodb+srv://hoangvutrannn:77pCHwjv1OwdqKuh@cluster1.7plzt.mongodb.net/?retryWrites=true&w=majority
    
networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
